"""Lybra's own vulnerability engine — the code that makes it a scanner.

This package holds everything that makes Lybra a scanner in its own right,
rather than an orchestrator that just runs Nmap and Nikto. By project
convention the managers live in ``themis/managers.py`` and the repositories in
``themis/repositories.py``; the detection logic lives here.

A scan flows down through the engine's layers, and each module here owns one of
them:

``transport``
    Discovers which ports are open — an unprivileged asyncio connect scan.

``fingerprinting``
    Identifies what is running on a port — one dissector module per
    protocol (HTTP, SSH, TLS, FTP, SMTP/IMAP/POP3, SMB, MySQL, Redis, VNC...),
    calibrated against Nmap where an oracle bench exists.

``engine``
    The detection core: turns discovered services into findings, including
    version-based CVE matches.

``checks``
    The active-detection runtime: runs declarative checks to *confirm* a
    vulnerability rather than merely infer it.

``kb``
    The local knowledge base: a mirror of NVD/KEV/EPSS plus the version and
    CPE logic the matcher relies on.

``correlation``
    Deduplication, lifecycle and contextual scoring: turns per-scan findings
    into vulnerability state on an asset over time.

``adapters``
    Bridges Nikto and Nuclei results into the shared ``Finding`` model, so every
    scanner can be correlated together.

``osint``
    La inteligencia pasiva: lo que Certificate Transparency, Shodan, Censys o
    SecurityTrails ya saben de un dominio, sin tocar el objetivo. Las fuentes
    llegan por un fetcher inyectado.

``api_surface``
    La superficie de una API a partir de su especificación OpenAPI/Swagger:
    parsea el documento y deriva los checks de sus endpoints, con un tope duro.

``dns_hygiene``
    Lo que un dominio publica en su DNS sobre su correo y sus certificados
    (SPF, DMARC, DKIM, MTA-STS, CAA, DNSSEC), con la búsqueda DNS inyectada.

Everything here is deliberately free of the ORM and of network side effects
where it can be: pure functions take plain values and return plain dicts, and the
few pieces that must touch the network (the probes and fetchers) take injectable
callables so they can be tested without it.

El análisis web activo (DAST-lite) también está archivado, no pendiente: la
decisión, con qué haría falta para reabrirla, está en el docstring de
``crawler.py``.
"""

from __future__ import annotations

from .engine import (
    LybraEngine,
    Service,
    services_from_payload,
    QOD_OPEN_PORT,
    QOD_INVENTORY_MATCH,
    CPE_PRODUCT_OVERRIDES,
)
from .grouping import (
    ServiceGroup,
    build_service_rollup,
    group_label,
)
from .backports import apply_backport_verdicts, is_unverified_distro_package, BACKPORT_CHECK_ID
from .distro import infer_distro_release, DistroRelease
from .compliance import (
    AttackTechnique,
    ComplianceControl,
    ComplianceFramework,
    FindingCompliance,
    list_compliance_frameworks,
    load_compliance_catalog,
    map_finding_compliance,
)
from .kb import (
    version_compare,
    split_distro_version,
    KB_MARK_SOURCES,
    kb_feed_version,
    parse_kb_feed_version,
    version_in_range,
    normalize_cpe_to_23,
    normalize_product_name,
    extract_trailing_version,
    load_product_aliases,
    parse_cpe23,
    ingest_nvd_cve,
    ingest_kev,
    parse_epss_rows,
    parse_oval_definitions,
    parse_csaf_advisory,
    fetch_oval,
    fetch_kev,
    fetch_epss,
    fetch_document,
    iter_nvd_pages,
)
from .osint import (
    CREDENTIALED_SOURCES,
    PASSIVE_EXPOSURE_CATEGORY,
    QOD_THIRD_PARTY,
    FetchedDocument,
    OsintSource,
    PassiveReport,
    ServiceObservation,
    SourceOutcome,
    SourceSetting,
    SourceStatus,
    SubdomainRecord,
    collect_host_observations,
    collect_passive_intelligence,
    finding_to_osint_json,
    normalize_domain,
    suggest_cpe_findings,
)
from .dns_hygiene import (
    DNS_HYGIENE_CATEGORY,
    QOD_DNS_RECORD,
    DnsCheckResult,
    DnsCheckStatus,
    assess_dns_hygiene,
    is_valid_dkim_selector,
)
from .checks import (
    load_checks,
    validate_checks,
    CheckRuntime,
    HttpProbe,
    HostRateLimiter,
    NetworkProbe,
    NetworkSession,
    Response,
    is_http_service,
    is_tls_service,
    is_ftp_service,
    is_smtp_service,
    is_imap_service,
    is_pop3_service,
    is_smb_service,
    is_mysql_service,
    is_redis_service,
    is_vnc_service,
    CHECKS_FEED_VERSION,
    QOD_CONFIRMED,
    ScriptContext,
    ScriptPlugin,
)
from .script_checks import (
    SmbSigningNotRequiredPlugin,
    SnmpDefaultCommunityPlugin,
    default_script_plugins,
)
from .credentials import (
    load_credentials,
    validate_credentials,
    CredentialRuntime,
    CredentialEntry,
    CredentialPair,
    CREDENTIALS_FEED_VERSION,
)
from .correlation import (
    classify_exposure,
    compute_dedup_key,
    merge_findings,
    apply_lifecycle,
    apply_refutations,
    split_refutations,
    score_finding,
    PRIORITY_LADDER,
)
from .fingerprinting import (
    Dissector,
    DissectorResult,
    default_dissectors,
    fingerprint_http,
    fingerprint_ssh,
    parse_ssh_banner,
    parse_kexinit,
    compute_hassh_server,
    load_tech_signatures,
    SshProbe,
    SshDissector,
    HttpDissector,
    TlsProbe,
    HttpFingerprint,
    SshFingerprint,
    TlsInfo,
    TechSignature,
    TechMatcher,
    SignatureHit,
    build_smb1_negotiate,
    parse_smb1_negotiate_response,
    build_ntlm_negotiate,
    build_session_setup_request,
    parse_ntlm_challenge,
    identify_unknown_service,
    read_volunteered_banner,
    FaviconCatalog,
    favicon_hash,
    load_favicon_hashes,
    validate_favicon_hashes,
    VersionReading,
    VERSION_SOURCES,
    validate_tech_signatures,
    FtpFingerprint,
    parse_ftp_banner,
    fingerprint_ftp,
    FtpProbe,
    FtpDissector,
    MailFingerprint,
    parse_smtp_banner,
    fingerprint_smtp,
    fingerprint_imap,
    fingerprint_pop3,
    MailProbe,
    SmtpDissector,
    ImapDissector,
    Pop3Dissector,
    SmbFingerprint,
    parse_negotiate_response,
    fingerprint_smb,
    SmbProbe,
    SmbDissector,
    MysqlFingerprint,
    parse_mysql_handshake,
    fingerprint_mysql,
    MysqlProbe,
    MysqlDissector,
    RedisFingerprint,
    parse_redis_info,
    fingerprint_redis,
    RedisProbe,
    RedisDissector,
    VncFingerprint,
    parse_rfb_version,
    fingerprint_vnc,
    VncProbe,
    VncDissector,
    SnmpFingerprint,
    parse_snmp_sysdescr,
    fingerprint_snmp,
    SnmpProbe,
    SnmpDissector,
    QOD_FINGERPRINT,
)
from .adapters import (
    nikto_incident_to_finding,
    nuclei_result_to_finding,
    finding_to_json,
    QOD_NUCLEI_MATCH,
)
from .exporters import (
    to_sarif,
    to_stix,
    to_ocsf,
)
from .planner import IDENTIFICATION_REVISION, CheckPlanner, KnownService
from .crawler import CrawlResult, crawl
from .api_surface import (
    ApiEndpoint,
    ApiSpecification,
    SPECIFICATION_PATHS,
    derive_checks as derive_api_checks,
    parse_specification,
)
from .virtual_hosts import (
    DEFAULT_SITE_CATEGORIES,
    SiteView,
    has_own_named_sites,
    is_alias_of_default_site,
    depends_on_site,
    mark_alias_fixes,
    mark_default_site_findings,
    select_site_names,
    site_finding,
)
from .transport import (
    AsyncConnectScanner,
    PortOutcome,
    PortSweep,
    scan_ports_sync,
    sweep_with_retries,
    sweep_ports_sync,
    scan_udp_ports_sync,
    services_from_discovered_ports,
    is_sweep_implausible,
    pinned_resolution,
    tcp_timestamps_enabled,
    DEFAULT_PORTS,
    UDP_PROBES,
    WELL_KNOWN_PORTS,
)

__all__ = [
    "LybraEngine",
    "Service",
    "services_from_payload",
    "QOD_OPEN_PORT",
    "QOD_INVENTORY_MATCH",
    "version_compare",
    "split_distro_version",
    "KB_MARK_SOURCES",
    "kb_feed_version",
    "parse_kb_feed_version",
    "version_in_range",
    "normalize_cpe_to_23",
    "normalize_product_name",
    "extract_trailing_version",
    "load_product_aliases",
    "parse_cpe23",
    "apply_backport_verdicts",
    "is_unverified_distro_package",
    "BACKPORT_CHECK_ID",
    "AttackTechnique",
    "ComplianceControl",
    "ComplianceFramework",
    "FindingCompliance",
    "list_compliance_frameworks",
    "load_compliance_catalog",
    "map_finding_compliance",
    "infer_distro_release",
    "DistroRelease",
    "ServiceGroup",
    "build_service_rollup",
    "group_label",
    "CPE_PRODUCT_OVERRIDES",
    "ingest_nvd_cve",
    "ingest_kev",
    "parse_epss_rows",
    "parse_oval_definitions",
    "parse_csaf_advisory",
    "fetch_oval",
    "fetch_kev",
    "fetch_epss",
    "fetch_document",
    "iter_nvd_pages",
    "CREDENTIALED_SOURCES",
    "DNS_HYGIENE_CATEGORY",
    "PASSIVE_EXPOSURE_CATEGORY",
    "QOD_DNS_RECORD",
    "QOD_THIRD_PARTY",
    "DnsCheckResult",
    "DnsCheckStatus",
    "FetchedDocument",
    "OsintSource",
    "PassiveReport",
    "ServiceObservation",
    "SourceOutcome",
    "SourceSetting",
    "SourceStatus",
    "SubdomainRecord",
    "assess_dns_hygiene",
    "collect_host_observations",
    "collect_passive_intelligence",
    "finding_to_osint_json",
    "is_valid_dkim_selector",
    "normalize_domain",
    "suggest_cpe_findings",
    "load_checks",
    "validate_checks",
    "CheckRuntime",
    "HttpProbe",
    "HostRateLimiter",
    "NetworkProbe",
    "NetworkSession",
    "Response",
    "is_http_service",
    "is_tls_service",
    "is_ftp_service",
    "is_smtp_service",
    "is_imap_service",
    "is_pop3_service",
    "is_smb_service",
    "is_mysql_service",
    "is_redis_service",
    "is_vnc_service",
    "CHECKS_FEED_VERSION",
    "QOD_CONFIRMED",
    "ScriptContext",
    "ScriptPlugin",
    "SmbSigningNotRequiredPlugin",
    "SnmpDefaultCommunityPlugin",
    "default_script_plugins",
    "load_credentials",
    "validate_credentials",
    "CredentialRuntime",
    "CredentialEntry",
    "CredentialPair",
    "CREDENTIALS_FEED_VERSION",
    "classify_exposure",
    "compute_dedup_key",
    "merge_findings",
    "apply_lifecycle",
    "apply_refutations",
    "split_refutations",
    "score_finding",
    "PRIORITY_LADDER",
    "Dissector",
    "DissectorResult",
    "default_dissectors",
    "fingerprint_http",
    "fingerprint_ssh",
    "parse_ssh_banner",
    "parse_kexinit",
    "compute_hassh_server",
    "load_tech_signatures",
    "SshProbe",
    "SshDissector",
    "HttpDissector",
    "TlsProbe",
    "HttpFingerprint",
    "SshFingerprint",
    "TlsInfo",
    "TechSignature",
    "TechMatcher",
    "SignatureHit",
    "build_smb1_negotiate",
    "parse_smb1_negotiate_response",
    "build_ntlm_negotiate",
    "build_session_setup_request",
    "parse_ntlm_challenge",
    "identify_unknown_service",
    "read_volunteered_banner",
    "FaviconCatalog",
    "favicon_hash",
    "load_favicon_hashes",
    "validate_favicon_hashes",
    "VersionReading",
    "VERSION_SOURCES",
    "validate_tech_signatures",
    "FtpFingerprint",
    "parse_ftp_banner",
    "fingerprint_ftp",
    "FtpProbe",
    "FtpDissector",
    "MailFingerprint",
    "parse_smtp_banner",
    "fingerprint_smtp",
    "fingerprint_imap",
    "fingerprint_pop3",
    "MailProbe",
    "SmtpDissector",
    "ImapDissector",
    "Pop3Dissector",
    "SmbFingerprint",
    "parse_negotiate_response",
    "fingerprint_smb",
    "SmbProbe",
    "SmbDissector",
    "MysqlFingerprint",
    "parse_mysql_handshake",
    "fingerprint_mysql",
    "MysqlProbe",
    "MysqlDissector",
    "RedisFingerprint",
    "parse_redis_info",
    "fingerprint_redis",
    "RedisProbe",
    "RedisDissector",
    "VncFingerprint",
    "parse_rfb_version",
    "fingerprint_vnc",
    "VncProbe",
    "VncDissector",
    "SnmpFingerprint",
    "parse_snmp_sysdescr",
    "fingerprint_snmp",
    "SnmpProbe",
    "SnmpDissector",
    "QOD_FINGERPRINT",
    "nikto_incident_to_finding",
    "nuclei_result_to_finding",
    "finding_to_json",
    "QOD_NUCLEI_MATCH",
    "to_sarif",
    "to_stix",
    "to_ocsf",
    "CheckPlanner",
    "KnownService",
    "IDENTIFICATION_REVISION",
    "AsyncConnectScanner",
    "PortOutcome",
    "PortSweep",
    "scan_ports_sync",
    "sweep_with_retries",
    "sweep_ports_sync",
    "scan_udp_ports_sync",
    "services_from_discovered_ports",
    "is_sweep_implausible",
    "pinned_resolution",
    "tcp_timestamps_enabled",
    "DEFAULT_SITE_CATEGORIES",
    "SiteView",
    "has_own_named_sites",
    "is_alias_of_default_site",
    "depends_on_site",
    "mark_alias_fixes",
    "mark_default_site_findings",
    "select_site_names",
    "site_finding",
    "CrawlResult",
    "crawl",
    "ApiEndpoint",
    "ApiSpecification",
    "SPECIFICATION_PATHS",
    "derive_api_checks",
    "parse_specification",
    "DEFAULT_PORTS",
    "UDP_PROBES",
    "WELL_KNOWN_PORTS",
]
